name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install modules
      run: npm install
    - name: Compile & distribute assets
      run: npm run start
  
